package com.test.ave;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2022-05-28T02:17:42.453-03:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://ave.com/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @WebMethod
    @Action(input = "http://ave.com/Hello/bonjourRequest", output = "http://ave.com/Hello/bonjourResponse")
    @RequestWrapper(localName = "bonjour", targetNamespace = "http://ave.com/", className = "com.ave.Bonjour")
    @ResponseWrapper(localName = "bonjourResponse", targetNamespace = "http://ave.com/", className = "com.ave.BonjourResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bonjour(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
