package com.test.ave;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2022-05-28T02:17:42.519-03:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "servicio_saludar",
                  wsdlLocation = "file:/C:/ALABURAR/proyecto-web/src/main/resources/dataaccess-numberconversion.wsdl",
                  targetNamespace = "http://ave.com/")
public class ServicioSaludar extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ave.com/", "servicio_saludar");
    public final static QName HelloPort = new QName("http://ave.com/", "HelloPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/ALABURAR/proyecto-web/src/main/resources/dataaccess-numberconversion.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioSaludar.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/ALABURAR/proyecto-web/src/main/resources/dataaccess-numberconversion.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioSaludar(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioSaludar(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSaludar() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicioSaludar(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioSaludar(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioSaludar(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort() {
        return super.getPort(HelloPort, Hello.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort(WebServiceFeature... features) {
        return super.getPort(HelloPort, Hello.class, features);
    }

}
