package com.test.generate.login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2022-06-01T17:02:34.025-03:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "AuthServiceService",
                  wsdlLocation = "file:/C:/ALABURAR/proyecto-web/src/main/resources/login.wsdl",
                  targetNamespace = "http://services.ave.com/")
public class AuthServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.ave.com/", "AuthServiceService");
    public final static QName AuthServicePort = new QName("http://services.ave.com/", "AuthServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/ALABURAR/proyecto-web/src/main/resources/login.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/ALABURAR/proyecto-web/src/main/resources/login.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AuthServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IAuthRepository
     */
    @WebEndpoint(name = "AuthServicePort")
    public IAuthRepository getAuthServicePort() {
        return super.getPort(AuthServicePort, IAuthRepository.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAuthRepository
     */
    @WebEndpoint(name = "AuthServicePort")
    public IAuthRepository getAuthServicePort(WebServiceFeature... features) {
        return super.getPort(AuthServicePort, IAuthRepository.class, features);
    }

}
