package com.test.generate.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2022-06-01T17:02:33.961-03:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://repositories.ave.com/", name = "I_AuthRepository")
@XmlSeeAlso({ObjectFactory.class})
public interface IAuthRepository {

    @WebMethod
    @Action(input = "http://repositories.ave.com/I_AuthRepository/getTrueLoginRequest", output = "http://repositories.ave.com/I_AuthRepository/getTrueLoginResponse")
    @RequestWrapper(localName = "getTrueLogin", targetNamespace = "http://repositories.ave.com/", className = "com.ave.GetTrueLogin")
    @ResponseWrapper(localName = "getTrueLoginResponse", targetNamespace = "http://repositories.ave.com/", className = "com.ave.GetTrueLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean getTrueLogin(

        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
}
